language: node_js

node_js:
  - 10.5

cache:
  directories:
    - node_modules

stages:
  - test
  - name: build
    if: branch = master

jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: test
      services:
        - mysql
      before_install:
        - mysql -e 'CREATE DATABASE testing;'
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      script: npm run test
    - stage: build
      script: npm run build:server
    - stage: build
      script: npm run build:client

env:
  globals:
    - APP_SECRET=testing
    - TYPEORM_USERNAME=travis
    - TYPEORM_DATABASE=testing
    - NODE_ENV=testing
